version: '3.4'
name: message-brokers

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./local-resources/rabbitmq/data:/var/lib/rabbitmq
      - ./local-resources/rabbitmq/.config:/etc/rabbitmq/rabbitmq.config
    env_file:
      - ./env/.rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  rabbitmq-publisher:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    environment:
      - PORT=3000
      - RABBITMQ_ENDPOINT=amqp://admin:admin@localhost
    ports:
      - '3000:3000'
    command: nx serve rabbitmq
    depends_on:
      - rabbitmq

volumes:
  root-node_modules: null
