version: '3'

services:
  nx-app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - root-node_modules:/app/node_modules

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.dockerfile
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    env_file:
      - ./env/.rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1m

  kafka:
    image: apache/kafka:3.7.0
    env_file:
      - ./env/.kafka
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1m
