version: '3.4'
name: message-brokers

services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./local-resources/rabbitmq/data:/var/lib/rabbitmq
      - ./local-resources/rabbitmq/.config:/etc/rabbitmq/rabbitmq.config
    env_file:
      - ./env/.rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1m

  rabbitmq-publisher:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    env_file:
      - ./env/.rabbitmq
    ports:
      - '3000:3000'
    command: nx serve rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "node healthcheck.js http://localhost:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1m
    depends_on:
      rabbitmq:
        condition: service_healthy

  rbmq-consumer:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    env_file:
      - ./env/.rabbitmq
    command: nx run rbmq-consumer:serve --args="${ARGS}"
    depends_on:
      rabbitmq-publisher:
        condition: service_healthy

volumes:
  root-node_modules: null
