
# Add animals
POST {{rabbitmqPublisherHost}}/animals
{{jsonContentType}}

{
  "animal": {
    "name": "🐶 pug #{{$randomInt 1 9999}}",
    "seconds": {{$randomInt 0 10}}
  },
  "types": "dog"
}
###

# Add fruits
POST {{rabbitmqPublisherHost}}/fruits
{{jsonContentType}}

{
  "fruit": {
    "name": "🍏 apple #{{$randomInt 1 9999}}",
    "seconds": {{$randomInt 0 10}}
  },
  "types": "apple"
}
###

# Add colors
POST {{rabbitmqPublisherHost}}/colors
{{jsonContentType}}

{
  "color": {
    "name": "🟫 brown #{{$randomInt 1 9999}}",
    "seconds": {{$randomInt 0 10}}
  },
  "types": "brown"
}
###
