import { getEnv } from '@message-brokers-lab/env';

export default getEnv<
  // rabbitmq consumers
  | 'RABBITMQ_ENDPOINT'
  | 'X_LOGS'
  | 'X_COLORS'
  | 'X_ORGANISMS'
  | 'Q_BLACK'
  | 'Q_BROWN'
  | 'Q_APPLES'
  | 'Q_ANIMALS'
  | 'Q_EVERYTHING'
  | 'RABBITMQ_STREAM_HOSTNAME'
  | 'RABBITMQ_STREAM_PORT'
  | 'RABBITMQ_STREAM_USERNAME'
  | 'RABBITMQ_STREAM_PASSWORD'
  | 'RABBITMQ_STREAM_VHOST'
  | 'RABBITMQ_STREAM_COLORS_NAME'
  | 'RABBITMQ_STREAM_LOGS_NAME'

  // kafka consumers
  | 'KAFKA_PROCESS_ROLES'
  | 'KAFKA_LISTENERS'
  | 'KAFKA_LISTENER_SECURITY_PROTOCOL_MAP'
  | 'KAFKA_CONTROLLER_LISTENER_NAMES'

  | 'CONSUMER_APP_ID'
  | 'CONSUMER_GROUP_ID'
  | 'KAFKA_BROKERS'
  | 'LOGS_TOPIC'
  | 'COLORS_TOPIC'
>;
